language: objective-c
osx_image: xcode7.2
os:
  - linux
  - osx
sudo: required
dist: trusty
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install carthage ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then carthage bootstrap ; fi
env:
  - SWIFT_VERSION=swift-2.2-SNAPSHOT-2016-01-06-a
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xctool test -workspace SwiftFoundation.xcworkspace -scheme "SwiftFoundation OS X" -sdk macosx ONLY_ACTIVE_ARCH=NO ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xctool test -workspace SwiftFoundation.xcworkspace -scheme "SwiftFoundation iOS" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO ; fi
  
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir swift ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl https://swift.org/builds/ubuntu1404/$SWIFT_VERSION/$SWIFT_VERSION-ubuntu14.04.tar.gz -s | tar xz -C swift &> /dev/null ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=$(pwd)/swift/$SWIFT_VERSION-ubuntu14.04/usr/bin:"${PATH}" ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; swift build ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then .build/debug/UnitTests ; fi